### ISSUE TITLE
cifar-10-batches-py sources

### ISSUE THREAD

**Issue by theblackcat102** [dterjek/adversarial_lipschitz_regularization#1]
@dterjek Is there an example code to generate cifar-10-batches pickled data? I can't seem to find any example else where on how to create cidar10 cache

**Comment by theblackcat102** [comment]
The cache from this [repo](https://github.com/0Colin/cifar-10-batches-py) seems to work well

**Comment by dterjek** [comment]
you can download the original from Alex Krizhevsky's site: https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
or you can use torchvision to do it for you: https://pytorch.org/vision/stable/datasets.html#cifar
and the one you linked seems to be fine as well
